export const ROUTES = {
  HOME: "/home",
  DISCOVER: "/discover",
  ALBUMS: "/albums",
  ALBUM: "/albums/:album",
  ARTISTS: "/artists",
  ARTIST: "/artists/:artistId",
  FAVOURITES: "/favorites",
  RECENTLY_ADDED: "/recently-added",
  LOGIN: "/login",
  REGISTRATION: "/registration",
  ACCOUNT_ACTIVATED: "/account-activated",
  ADMIN_TRACKS: "/admin-tracks",
  ADMIN_ALBUMS: "/admin-albums",
  ADMIN_ARTISTS: "/admin-artists",
};
